/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { MeshTransmissionMaterial, useGLTF } from "@react-three/drei"
import React from "react"
import modelUrl from "../assets/models/WawaCard.glb?url"

export function BankCard({ transmissionSettings, ...props }) {
  const { nodes, materials } = useGLTF(modelUrl)

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.glass}
        rotation={[0, -1.571, 0]}
      >
        <MeshTransmissionMaterial
          {...transmissionSettings}
          toneMapped={false}
          
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.number_.geometry}
          material={materials["white shiny"]}
          position={[0.145, 0.01, 0.705]}
          rotation={[0, 1.571, 0]}
          scale={0.172}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text.geometry}
          material={materials.logo}
          position={[-0.318, 0.012, -0.632]}
          rotation={[0, 1.571, 0]}
          scale={0.403}
        /> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text002.geometry}
          material={materials["white.001"]}
          position={[0.423, 0.009, -0.534]}
          rotation={[0, 1.571, 0]}
          scale={0.018}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text004.geometry}
          material={materials["white shiny"]}
          position={[0.427, 0.009, -0.542]}
          rotation={[0, 1.571, 0]}
          scale={0.064}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.wawa_sensei_3.geometry}
          material={materials["white shiny"]}
          position={[0.435, 0.009, 0.694]}
          rotation={[0, 1.571, 0]}
          scale={0.097}
        /> */}
      </mesh>
    </group>
  );
}

useGLTF.preload(modelUrl);
