/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/Cactoro.gltf -o src/components/Cactoro.jsx -r src 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import cactoroUrl from '../assets/models/Cactoro.gltf?url'

export function Cactoro({hovered, ...props}) {
    const group = React.useRef()
    const { scene, animations } = useGLTF(cactoroUrl)
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
    const { nodes, materials } = useGraph(clone)
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        if(!actions) return
  
        const anim = hovered ? "Dance" : "Idle"
        const act = actions[anim]
  
        if(!act) return
          
        act.reset().fadeIn(0.5).play()
        return () => act?.fadeOut?.(0.5)
      }, [hovered, actions])

    return (
        <group ref={group} {...props} dispose={null}>
        <group name="Scene">
            <group name="CharacterArmature">
                <primitive object={nodes.Body} />
                <primitive object={nodes.Head} />
                <skinnedMesh name="Cactoro_Blob" geometry={nodes.Cactoro_Blob.geometry} material={materials.Atlas} skeleton={nodes.Cactoro_Blob.skeleton} />
                <skinnedMesh name="Cactoro_Blob001" geometry={nodes.Cactoro_Blob001.geometry} material={materials.Atlas} skeleton={nodes.Cactoro_Blob001.skeleton} />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(cactoroUrl)
