/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/Horse_White.gltf -o src/components/Horse.jsx -r src 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import horseUrl from "../assets/models/Horse_White.gltf?url"

export function Horse({ hovered, ...props}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF(horseUrl)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
            if (!actions) return
        
            const idleName = "Idle"      // default pose
            const hoverName = "Attack_Kick"     // when hovered
            const targetName = hovered ? hoverName : idleName
            const targetAction = actions[targetName]
        
            console.log("Horse hovered:", hovered, "→ playing:", targetName)
            console.log("Available clips:", names)
        
            if (!targetAction) {
              console.warn("No action found for", targetName)
              return
            }
        
            // stop everything else, then play the target
            Object.values(actions).forEach((a) => a?.stop?.())
        
            targetAction.reset().fadeIn(0.3).play()
        
            return () => {
              targetAction.fadeOut?.(0.3)
            }
  }, [hovered, actions, names])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.IKBackLegL} />
          <primitive object={nodes.IKFrontLegL} />
          <primitive object={nodes.IKBackLegR} />
          <primitive object={nodes.IKFrontLegR} />
          <group name="Horse">
            <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Main} skeleton={nodes.Cube.skeleton} />
            <skinnedMesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.Main_Light} skeleton={nodes.Cube_1.skeleton} />
            <skinnedMesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials.Hooves} skeleton={nodes.Cube_2.skeleton} />
            <skinnedMesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials.Hair} skeleton={nodes.Cube_3.skeleton} />
            <skinnedMesh name="Cube_4" geometry={nodes.Cube_4.geometry} material={materials.Muzzle} skeleton={nodes.Cube_4.skeleton} />
            <skinnedMesh name="Cube_5" geometry={nodes.Cube_5.geometry} material={materials.Eye_White} skeleton={nodes.Cube_5.skeleton} />
            <skinnedMesh name="Cube_6" geometry={nodes.Cube_6.geometry} material={materials.Eye_Black} skeleton={nodes.Cube_6.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(horseUrl)
