/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/Husky.gltf -o src/components/Husky.jsx -r src 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import huskyUrl from "../assets/models/Husky.gltf?url"

export function Husky({hovered, ...props}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF(huskyUrl)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
        if (!actions) return
    
        const idleName = "Idle"      // default pose
        const hoverName = "Gallop"     // when hovered
        const targetName = hovered ? hoverName : idleName
        const targetAction = actions[targetName]
    
        // console.log("Husky hovered:", hovered, "→ playing:", targetName)
        // console.log("Available clips:", names)
    
        if (!targetAction) {
          console.warn("No action found for", targetName)
          return
        }
    
        // stop everything else, then play the target
        Object.values(actions).forEach((a) => a?.stop?.())
    
        targetAction.reset().fadeIn(0.3).play()
    
        return () => {
          targetAction.fadeOut?.(0.3)
        }
      }, [hovered, actions, names])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.IKBackLegL} />
          <primitive object={nodes.IKFrontLegL} />
          <primitive object={nodes.IKBackLegR} />
          <primitive object={nodes.IKFrontLegR} />
          <group name="Cube">
            <skinnedMesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.Material} skeleton={nodes.Cube_1.skeleton} />
            <skinnedMesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials['Material.006']} skeleton={nodes.Cube_2.skeleton} />
            <skinnedMesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials['Material.001']} skeleton={nodes.Cube_3.skeleton} />
            <skinnedMesh name="Cube_4" geometry={nodes.Cube_4.geometry} material={materials['Material.002']} skeleton={nodes.Cube_4.skeleton} />
            <skinnedMesh name="Cube_5" geometry={nodes.Cube_5.geometry} material={materials['Material.003']} skeleton={nodes.Cube_5.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(huskyUrl)
