/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/Ninja.gltf -o src/components/Ninja.jsx -r src 
*/

import React, { useEffect, useMemo, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import ninjaUrl from '../assets/models/Ninja.gltf?url'

export function Ninja({ hovered, ...props }) {
    const group = React.useRef()
    const { scene, animations } = useGLTF(ninjaUrl)
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
    const { nodes, materials } = useGraph(clone)
    const { actions, names } = useAnimations(animations, group)

    useEffect(() => {
        if(!actions) return
  
        const anim = hovered ? "Weapon" : "Idle"
        const act = actions[anim]
  
        if(!act) return
          
        act.reset().fadeIn(0.5).play()
        return () => act?.fadeOut?.(0.5)
    }, [hovered, actions])

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="CharacterArmature">
                    <primitive object={nodes.Root} />
                    <skinnedMesh name="Ninja" geometry={nodes.Ninja.geometry} material={materials.Atlas} skeleton={nodes.Ninja.skeleton} />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(ninjaUrl)
